version: "3.7"
services:
  postgresql:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pa55Word!
      POSTGRES_USER: demo
      POSTGRES_DB: demodb