namespace: db
commonLabels:
  app: postgresql
secretGenerator:
  - name: pgsql-credentials
    literals:
      - username=demo
      - password=pa55Word!
      - database=demodb
      - hostname=postgresql.db.svc.cluster.local
      - port=5432
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - dbadminer.yaml
  - service.yaml
  - dbadminer-service.yaml